import { Group } from "lucide-react";

export type IconDisplyName =
  | keyof typeof SVG_ICONS_REGISTERY
  | keyof typeof PNG_ICONS_REGISTERY;

export const SVG_ICONS_REGISTERY = {
  // lucid
  // Download, Upload, TerminalSquare, Database, ListFilter, BrainCircuit, Layers, Binary, Bot, Link, Paperclip, Link2, Cpu, Compass, FlaskConical, File
  Download: "/assets/icons/download.svg",
  Upload: "/assets/icons/upload.svg",
  TerminalSquare: "/assets/icons/square-terminal.svg",

  Directory: "/assets/icons/folder.svg",
  File: "/assets/icons/file-text.svg",
  URL: "/assets/icons/link.svg",
  Webhook: "/assets/icons/webhook.svg",
  Text: "/assets/icons/type.svg",
  Database: "/assets/icons/database.svg",
  Globe: "/assets/icons/globe.svg",
  Route: "/assets/icons/route.svg",
  FolderSync: "/assets/icons/folder-sync.svg",
  ListFilter: "/assets/icons/list-filter.svg",
  BrainCircuit: "/assets/icons/brain-circuit.svg",
  Layers: "/assets/icons/layers.svg",
  Binary: "/assets/icons/binary.svg",
  Bot: "/assets/icons/bot.svg",
  Cpu: "/assets/icons/cpu.svg",
  Hammer: "/assets/icons/hammer.svg",
  Wand2: "/assets/icons/wand-sparkles.svg",
  ArrowRightLeft: "/assets/icons/arrow-right-left.svg",
  MessagesSquare: "/assets/icons/messages-square.svg",
  MessagesSquareShare: "/assets/icons/message-square-share.svg",
  CircleAlert: "/assets/icons/circle-alert.svg",
  Split: "/assets/icons/split.svg",
  Calculator: "/assets/icons/calculator.svg",
  AIML: "/bundles-icons/AI-ML.svg",
  Anthropic: "/bundles-icons/anthropic.svg",
  Azure: "/bundles-icons/azure.png",
  Deepseek: "/bundles-icons/deepseek.svg",
  Bedrok: "/bundles-icons/aws2.svg",
  Groq: "/bundles-icons/Groq.svg",
  Huggingface: "/bundles-icons/huggingface.svg",
  LMStudio: "/bundles-icons/LMStudio.png",
  Maritalk: "/bundles-icons/maritalk.svg",
  Mistral: "/bundles-icons/mistral.svg",
  Novita: "/bundles-icons/novita.svg",
  Ollama: "/bundles-icons/Ollama.svg",
  OpenAI: "/bundles-icons/openAI.svg",
  OpenRouter: "/bundles-icons/openrouter.svg",
  Preplexity: "/bundles-icons/preplexity.svg",
  Qianfan: "/bundles-icons/QianFanChat.svg",
  SambaNova: "/bundles-icons/sambanova.svg", // SambaNovaLogo.svg
  VertexAI: "/bundles-icons/vertexAI.svg",
  XAI: "/bundles-icons/xai.svg",
  Astra: "/bundles-icons/datastax.webp",
  Cassandra: "/bundles-icons/cassandra.png",
  Chroma: "/bundles-icons/chroma.svg",
  ClickHouse: "/bundles-icons/clickhouse.svg",
  Couchbase: "/bundles-icons/couchbase.svg",
  Elasticsearch: "/bundles-icons/elasticsearch.svg",
  Meta: "/bundles-icons/meta-icon.svg",
  Milvus: "/bundles-icons/milvus.png",
  PGVector: "/bundles-icons/Postgres.svg",
  Pinecone: "/bundles-icons/pinecone_logo.svg",
  Qdrant: "/bundles-icons/QDrant.svg",
  Redis: "/bundles-icons/Redis.svg",
  Supabase: "/bundles-icons/supabase-icon.svg",
  Upstash: "/bundles-icons/upstash.svg",
  Vectra: "/bundles-icons/vectra.png",
  Weaviate: "/bundles-icons/weaviate.svg",
  Mem0: "/bundles-icons/mem0.svg",
  Zep: "/bundles-icons/zep-memory.svg",
  Bing: "/bundles-icons/bing.svg",
  DuckSearch: "/bundles-icons/duckduckgo.svg",
  EXa: "/bundles-icons/exa.svg",
  GleanSearch: "/bundles-icons/glean.svg",
  MCP: "/assets/icons/code.svg",
  OpenSearch: "/bundles-icons/opensearch.svg",
  Python: "/bundles-icons/Python.svg",
  Serper: "/bundles-icons/serper.svg",
  SearchAPI: "/bundles-icons/searchapi.png",
  Tavily: "/bundles-icons/tavily.svg",
  Wikidata: "/bundles-icons/wikidata.svg",
  Wikipedia: "/bundles-icons/Wikipedia.svg",
  Wolframe: "/bundles-icons/wolframe.svg",
  Yahoo: "/assets/icons/trending-up.svg",
  ArXiv: "/bundles-icons/arxiv.svg",
  // Others
  LangChain: "/bundles-icons/langchain-icon.svg",
  AgentQL: "/bundles-icons/AgentQL.svg",
  AssemblyAI: "/bundles-icons/AssemblyAI.svg",
  DataStax: "/bundles-icons/datastax.webp",
  LangWatch: "/bundles-icons/langwatch-icon.svg",
  Notion: "/bundles-icons/Notion-logo.svg",
  Needle: "/bundles-icons/needle-icon.svg",
  NVIDIA: "/bundles-icons/nvidia.svg",
  Vectara: "/bundles-icons/vectra.png",
  "Icosa Computing": "/bundles-icons/Icosa.svg",
  Google: "/bundles-icons/google.svg",
  CrewAI: "/bundles-icons/crewai.png",
  NotDiamond: "/bundles-icons/notdiamond-icon.svg",
  Composio: "/bundles-icons/Composio.svg",
  Cohere: "/bundles-icons/cohere.svg",
  Firecrawl: "/bundles-icons/firecrawl.jpeg",
  Unstructured: "/bundles-icons/Unstructured.svg",
  Git: "/bundles-icons/Git.svg",
  Confluence: "/bundles-icons/Confluence.svg",
  // Confluence2: "/bundles-icons/Confluence.svg",
} as const;

export const PNG_ICONS_REGISTERY = {} as const;

export const ALL_ICONS = SVG_ICONS_REGISTERY;
