// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from '@hey-api/client-axios';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import { client, HealthCheckService, HomeService, ITemsRouterService } from '../sdk.gen';
import type { CreateItemRouteApiV1ItemPostData, CreateItemRouteApiV1ItemPostError, CreateItemRouteApiV1ItemPostResponse } from '../types.gen';
import type { AxiosError } from 'axios';

type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};

export const checkHealthApiV1HealthGetQueryKey = (options?: OptionsLegacyParser) => [
    createQueryKey('checkHealthApiV1HealthGet', options)
];

export const checkHealthApiV1HealthGetOptions = (options?: OptionsLegacyParser) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await HealthCheckService.checkHealthApiV1HealthGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: checkHealthApiV1HealthGetQueryKey(options)
    });
};

export const rootGetQueryKey = (options?: OptionsLegacyParser) => [
    createQueryKey('rootGet', options)
];

export const rootGetOptions = (options?: OptionsLegacyParser) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await HomeService.rootGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: rootGetQueryKey(options)
    });
};

export const getItemsRouteApiV1ItemGetQueryKey = (options?: OptionsLegacyParser) => [
    createQueryKey('getItemsRouteApiV1ItemGet', options)
];

export const getItemsRouteApiV1ItemGetOptions = (options?: OptionsLegacyParser) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ITemsRouterService.getItemsRouteApiV1ItemGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getItemsRouteApiV1ItemGetQueryKey(options)
    });
};

export const createItemRouteApiV1ItemPostQueryKey = (options: OptionsLegacyParser<CreateItemRouteApiV1ItemPostData>) => [
    createQueryKey('createItemRouteApiV1ItemPost', options)
];

export const createItemRouteApiV1ItemPostOptions = (options: OptionsLegacyParser<CreateItemRouteApiV1ItemPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ITemsRouterService.createItemRouteApiV1ItemPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createItemRouteApiV1ItemPostQueryKey(options)
    });
};

export const createItemRouteApiV1ItemPostMutation = (options?: Partial<OptionsLegacyParser<CreateItemRouteApiV1ItemPostData>>) => {
    const mutationOptions: UseMutationOptions<CreateItemRouteApiV1ItemPostResponse, AxiosError<CreateItemRouteApiV1ItemPostError>, OptionsLegacyParser<CreateItemRouteApiV1ItemPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await ITemsRouterService.createItemRouteApiV1ItemPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};