// This file is auto-generated by @hey-api/openapi-ts

export type GetAllFlowComponentsTypesApiV1ComponentAllGetResponse = unknown;

export type GetAllFlowComponentsTypesApiV1ComponentAllGetError = unknown;

export type CheckHealthApiV1HealthGetResponse = unknown;

export type CheckHealthApiV1HealthGetError = unknown;

export type RootGetResponse = string;

export type RootGetError = unknown;
