// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  GetAllFlowComponentsTypesApiV1ComponentAllGetError,
  GetAllFlowComponentsTypesApiV1ComponentAllGetResponse,
  CheckHealthApiV1HealthGetError,
  CheckHealthApiV1HealthGetResponse,
  RootGetError,
  RootGetResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export class FlowComponentService {
  /**
   * Get All Flow Components Types
   * get list of current provided components + the custom components the user created
   */
  public static getAllFlowComponentsTypesApiV1ComponentAllGet<
    ThrowOnError extends boolean = false
  >(options?: OptionsLegacyParser<unknown, ThrowOnError>) {
    return (options?.client ?? client).get<
      GetAllFlowComponentsTypesApiV1ComponentAllGetResponse,
      GetAllFlowComponentsTypesApiV1ComponentAllGetError,
      ThrowOnError
    >({
      ...options,
      url: "/api/v1/component/all",
    });
  }
}

export class HealthCheckService {
  /**
   * Check Health
   */
  public static checkHealthApiV1HealthGet<ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      CheckHealthApiV1HealthGetResponse,
      CheckHealthApiV1HealthGetError,
      ThrowOnError
    >({
      ...options,
      url: "/api/v1/health/",
    });
  }
}

export class HomeService {
  /**
   * Root
   */
  public static rootGet<ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      RootGetResponse,
      RootGetError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  }
}
