// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  CheckHealthApiV1HealthGetError,
  CheckHealthApiV1HealthGetResponse,
  RootGetError,
  RootGetResponse,
  GetItemsRouteApiV1ItemGetError,
  GetItemsRouteApiV1ItemGetResponse,
  CreateItemRouteApiV1ItemPostData,
  CreateItemRouteApiV1ItemPostError,
  CreateItemRouteApiV1ItemPostResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export class HealthCheckService {
  /**
   * Check Health
   */
  public static checkHealthApiV1HealthGet<ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      CheckHealthApiV1HealthGetResponse,
      CheckHealthApiV1HealthGetError,
      ThrowOnError
    >({
      ...options,
      url: "/api/v1/health/",
    });
  }
}

export class HomeService {
  /**
   * Root
   */
  public static rootGet<ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      RootGetResponse,
      RootGetError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  }
}

export class ITemsRouterService {
  /**
   * Get Items Route
   */
  public static getItemsRouteApiV1ItemGet<ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetItemsRouteApiV1ItemGetResponse,
      GetItemsRouteApiV1ItemGetError,
      ThrowOnError
    >({
      ...options,
      url: "/api/v1/item/",
    });
  }

  /**
   * Create Item Route
   */
  public static createItemRouteApiV1ItemPost<
    ThrowOnError extends boolean = false
  >(
    options: OptionsLegacyParser<CreateItemRouteApiV1ItemPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CreateItemRouteApiV1ItemPostResponse,
      CreateItemRouteApiV1ItemPostError,
      ThrowOnError
    >({
      ...options,
      url: "/api/v1/item/",
    });
  }
}
