// This file is auto-generated by @hey-api/openapi-ts

export type Category = {
    name: string;
    description: string;
};

export type CreateItemSchema = {
    name: string;
    /**
     * Optional description of the item
     */
    description?: (string | null);
    price: number;
    category: Category;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CheckHealthApiV1HealthGetResponse = (unknown);

export type CheckHealthApiV1HealthGetError = unknown;

export type RootGetResponse = (string);

export type RootGetError = unknown;

export type GetItemsRouteApiV1ItemGetResponse = (unknown);

export type GetItemsRouteApiV1ItemGetError = unknown;

export type CreateItemRouteApiV1ItemPostData = {
    body: CreateItemSchema;
};

export type CreateItemRouteApiV1ItemPostResponse = (unknown);

export type CreateItemRouteApiV1ItemPostError = (HTTPValidationError);